export const polishVersion = {
  welcomeDescription:
    "Rysuj i zgaduj hasła z przyjaciółmi w czasie rzeczywistym!",
  usernameLabel: "Nazwa",
  roomIdLabel: "ID pokoju",
  createRoom: "Stwórz pokój",
  or: "LUB",
  joinRoom: "Dołącz do pokoju",
  join: "Dołącz",
  leaderboard: "Tabela",
  points: "punktów",
  leave: "Wyjdź",
  clear: "Wyczyść",
  strokeWidth: "Grubość pędzla",
  gameSettings: "Ustawienia gry",
  gameSettingsDescription: "Wybierz czas rysowania i liczbę rund!",
  drawtimeLabel: "Czas",
  roundsLabel: "Rundy",
  play: "Graj",
  cantStart: "Nie możesz wystartować gry :(",
  cantStartDescription:
    "Jesteś sam w tym pokoju. Zaproś więcej osób żeby zagrać.",
  chat: "Czat",
  guesssed: "zgadł hasło !",
  message: "Wiadomość",
  drawThis: "Narysuj",
  guessThis: "Zgadnij",
  wordWas: "Hasło to",
  choosingTheWord: "wybiera hasło",
  waiting: "Czekanie na gospodarza",
  winner: "zwycięża !",
  newGame: "Nowa Gra",
  light: "Jasny",
  dark: "Ciemny",
};

export const englishVersion = {
  welcomeDescription: "Draw and guess words with your friends in real time!",
  usernameLabel: "Username",
  roomIdLabel: "Room ID",
  createRoom: "Create a room",
  or: "OR",
  joinRoom: "Join a room",
  join: "Join",
  leaderboard: "Leaderboard",
  points: "points",
  leave: "Leave",
  clear: "Clear",
  strokeWidth: "Stroke Width",
  gameSettings: "Game settings",
  gameSettingsDescription: "Select draw time and number of round!",
  drawtimeLabel: "Drawtime",
  roundsLabel: "Rounds",
  play: "Play",
  cantStart: "You can't start game :(",
  cantStartDescription:
    "You are alone in that room. Invite more people to play.",
  chat: "Chat",
  guesssed: "guessed the word !",
  message: "Message",
  drawThis: "Draw this",
  guessThis: "Guess this",
  wordWas: "The word was",
  choosingTheWord: "is choosing the word",
  waiting: "Waiting for host to start game",
  winner: "is the winner!",
  newGame: "New Game",
  light: "Light",
  dark: "Dark",
};

export const textContent: Record<
  string,
  typeof englishVersion | typeof polishVersion
> = {
  PL: polishVersion,
  ENG: englishVersion,
};
